######################################################################
# Automatically generated by qmake (2.01a) Wed May 14 16:23:59 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dialog.h \
    example.h
FORMS += dialog.ui \
    example.ui
SOURCES += dialog.cpp main.cpp \
    example.cpp
