#############################################################################
# Makefile for building: hello2
# Generated by qmake (2.01a) (Qt 4.8.5) on: Wed May 14 16:24:04 2014
# Project:  hello2.pro
# Template: app
# Command: /opt/emac/5.0.0/sysroots/i686-emacsdk-linux/usr/bin/qmake2 -spec /opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/qws/linux-x86-g++ -o Makefile hello2.pro
#############################################################################

####### Compiler, tools and options

CC            = $(OE_QMAKE_CC)
CXX           = $(OE_QMAKE_CXX)
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -pipe $(OE_QMAKE_CFLAGS) -O2 -Wall -W -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -pipe -pipe $(OE_QMAKE_CFLAGS) $(OE_QMAKE_CXXFLAGS) -O2 -O2 -Wall -W -Wall -W -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/qws/linux-x86-g++ -I. -I$(OE_QMAKE_INCDIR_QT)/QtCore -I$(OE_QMAKE_INCDIR_QT)/QtNetwork -I$(OE_QMAKE_INCDIR_QT)/QtGui -I$(OE_QMAKE_INCDIR_QT) -I. -I. -I.
LINK          = $(OE_QMAKE_LINK)
LFLAGS        = $(OE_QMAKE_LDFLAGS) -Wl,-rpath-link,$(OE_QMAKE_LIBDIR_QT)
LIBS          = $(SUBLIBS)  -L$(OE_QMAKE_LIBDIR_QT) -lQtGuiE -lQtNetworkE -lQtCoreE -lpthread 
AR            = $(OE_QMAKE_AR) cqs
RANLIB        = 
QMAKE         = /opt/emac/5.0.0/sysroots/i686-emacsdk-linux/usr/bin/qmake2
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = $(OE_QMAKE_STRIP)
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = dialog.cpp \
		main.cpp moc_dialog.cpp
OBJECTS       = dialog.o \
		main.o \
		moc_dialog.o
DIST          = /opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/common/unix.conf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/common/linux.conf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/common/gcc-base.conf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/common/gcc-base-unix.conf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/common/g++-unix.conf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/common/qws.conf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/qconfig.pri \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/modules/qt_webkit_version.pri \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/qt_functions.prf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/qt_config.prf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/exclusive_builds.prf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/default_pre.prf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/release.prf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/default_post.prf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/shared.prf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/warn_on.prf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/qt.prf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/unix/thread.prf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/moc.prf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/resources.prf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/uic.prf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/yacc.prf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/lex.prf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/include_source_dir.prf \
		hello2.pro
QMAKE_TARGET  = hello2
DESTDIR       = 
TARGET        = hello2

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_dialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: hello2.pro  /opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/qws/linux-x86-g++/qmake.conf /opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/common/unix.conf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/common/linux.conf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/common/gcc-base.conf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/common/gcc-base-unix.conf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/common/g++-unix.conf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/common/qws.conf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/qconfig.pri \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/modules/qt_webkit_version.pri \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/qt_functions.prf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/qt_config.prf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/exclusive_builds.prf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/default_pre.prf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/release.prf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/default_post.prf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/shared.prf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/warn_on.prf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/qt.prf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/unix/thread.prf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/moc.prf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/resources.prf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/uic.prf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/yacc.prf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/lex.prf \
		/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/qws/linux-x86-g++ -o Makefile hello2.pro
/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/common/unix.conf:
/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/common/linux.conf:
/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/common/gcc-base.conf:
/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/common/gcc-base-unix.conf:
/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/common/g++-unix.conf:
/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/common/qws.conf:
/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/qconfig.pri:
/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/modules/qt_webkit_version.pri:
/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/qt_functions.prf:
/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/qt_config.prf:
/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/exclusive_builds.prf:
/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/default_pre.prf:
/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/release.prf:
/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/default_post.prf:
/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/shared.prf:
/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/warn_on.prf:
/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/qt.prf:
/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/unix/thread.prf:
/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/moc.prf:
/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/resources.prf:
/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/uic.prf:
/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/yacc.prf:
/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/lex.prf:
/opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /opt/emac/5.0.0/sysroots/i586-emac-linux/usr/share/qtopia/mkspecs/qws/linux-x86-g++ -o Makefile hello2.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/hello21.0.0 || $(MKDIR) .tmp/hello21.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/hello21.0.0/ && $(COPY_FILE) --parents dialog.h .tmp/hello21.0.0/ && $(COPY_FILE) --parents dialog.cpp main.cpp .tmp/hello21.0.0/ && $(COPY_FILE) --parents dialog.ui .tmp/hello21.0.0/ && (cd `dirname .tmp/hello21.0.0` && $(TAR) hello21.0.0.tar hello21.0.0 && $(COMPRESS) hello21.0.0.tar) && $(MOVE) `dirname .tmp/hello21.0.0`/hello21.0.0.tar.gz . && $(DEL_FILE) -r .tmp/hello21.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_dialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_dialog.cpp
moc_dialog.cpp: dialog.h
	$(OE_QMAKE_MOC) $(DEFINES) $(INCPATH) dialog.h -o moc_dialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_dialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_dialog.h
ui_dialog.h: dialog.ui
	$(OE_QMAKE_UIC) dialog.ui -o ui_dialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

dialog.o: dialog.cpp dialog.h \
		ui_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o dialog.cpp

main.o: main.cpp dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

